# Generated by Django 2.2.3 on 2019-08-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20190802_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='topic',
        ),
        migrations.AddField(
            model_name='topic',
            name='article',
            field=models.ManyToManyField(related_name='article_topics', to='blog_app.Article'),
        ),
    ]
